const $=selector=>document.querySelector(selector);const $$=selector=>[...document.querySelectorAll(selector)];
const el={statusPill:$('#statusPill'),statusText:$('#statusText'),connectionBadge:$('#connectionBadge'),activeModel:$('#activeModel'),activeBackend:$('#activeBackend'),modelChip:$('#modelChip'),connectButton:$('#connectButton'),drawerConnect:$('#drawerConnect'),messages:$('#messages'),errorBanner:$('#errorBanner'),composerForm:$('#composerForm'),composerInput:$('#composerInput'),micButton:$('#micButton'),clearButton:$('#clearButton'),settingsToggle:$('#settingsToggle'),settingsClose:$('#settingsClose'),settingsDrawer:$('#settingsDrawer'),settingsScrim:$('#settingsScrim'),authMode:$('#authMode'),apiKeyGroup:$('#apiKeyGroup'),apiKey:$('#apiKey'),modelInput:$('#modelInput'),voiceInput:$('#voiceInput'),thinkingInput:$('#thinkingInput'),imageModelInput:$('#imageModelInput'),imageResolutionInput:$('#imageResolutionInput'),sendScreenshot:$('#sendScreenshot'),systemPrompt:$('#systemPrompt'),settingsSaved:$('#settingsSaved'),portValue:$('#portValue')};
const app={state:null,ws:null,wsRetry:null,settingsTimer:null,lastRevision:-1,mic:null,audioContext:null,playbackTime:0};
const backendLabels={codex_gpt_live:'Codex GPT Live',open_ai_realtime:'OpenAI Realtime',codex_text:'Codex Text'};
function escapeHtml(value=''){return value.replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[char]))}
function formatTime(seconds){return new Date(seconds*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
async function request(path,options={}){const hasBody=options.body!==undefined;const response=await fetch(path,{...options,headers:{...(hasBody?{'Content-Type':'application/json'}:{}),...(options.headers||{})}});const contentType=response.headers.get('content-type')||'';const payload=contentType.includes('application/json')?await response.json():await response.text();if(!response.ok)throw new Error(payload?.error||payload||`Request failed: ${response.status}`);return payload}
function connectWebSocket(){clearTimeout(app.wsRetry);const protocol=location.protocol==='https:'?'wss:':'ws:';const ws=new WebSocket(`${protocol}//${location.host}/ws`);ws.binaryType='arraybuffer';app.ws=ws;ws.onmessage=event=>{if(typeof event.data==='string'){try{const payload=JSON.parse(event.data);if(payload.type==='state')applyState(payload.state)}catch(error){console.warn('Invalid backend event',error)}return}playPcm(event.data)};ws.onclose=()=>{if(app.ws===ws)app.ws=null;app.wsRetry=setTimeout(connectWebSocket,1200)}}
function applyState(state){app.state=state;if(state.revision===app.lastRevision)return;app.lastRevision=state.revision;renderState(state)}
function renderState(state){const settings=state.settings;el.statusText.textContent=state.status;el.statusPill.className=`status-pill ${state.error?'error':state.connection}`;el.connectionBadge.textContent=state.connection.replace('_',' ');el.connectionBadge.className=`tiny-badge ${state.connection}`;el.activeModel.textContent=settings.model;el.activeBackend.textContent=backendLabels[settings.backend]||settings.backend;el.modelChip.textContent=settings.backend==='codex_text'?'Text':settings.backend==='open_ai_realtime'?'Realtime':'GPT Live';el.portValue.textContent=location.port||(location.protocol==='https:'?'443':'80');const connected=['live','connecting','reconnecting'].includes(state.connection);for(const button of[el.connectButton,el.drawerConnect]){button.textContent=connected?'Disconnect':'Connect';button.classList.toggle('disconnect',connected)}el.errorBanner.classList.toggle('hidden',!state.error);el.errorBanner.textContent=state.error||'';syncSettingsForm(settings);renderMessages(state.messages);$$('#backendSegments button').forEach(button=>button.classList.toggle('active',button.dataset.backend===settings.backend))}
function syncSettingsForm(settings){const focused=document.activeElement;const setUnlessFocused=(element,value)=>{if(focused!==element&&element.value!==String(value))element.value=value};setUnlessFocused(el.authMode,settings.auth_mode);setUnlessFocused(el.modelInput,settings.model);setUnlessFocused(el.voiceInput,settings.voice);setUnlessFocused(el.thinkingInput,settings.thinking_level);setUnlessFocused(el.imageModelInput,settings.image_model);setUnlessFocused(el.imageResolutionInput,settings.image_resolution);setUnlessFocused(el.systemPrompt,settings.system_prompt);el.sendScreenshot.checked=Boolean(settings.send_screenshot);el.apiKeyGroup.classList.toggle('hidden',settings.auth_mode!=='api_key')}
function renderMessages(messages){if(!messages.length){el.messages.innerHTML='<div class="empty-state"><div class="empty-state-inner"><div class="empty-orb"></div><h3>Ready when you are</h3><p>Connect a model, type a message, or start the microphone. The browser only renders state from the Rust runtime.</p></div></div>';return}const nearBottom=el.messages.scrollHeight-el.messages.scrollTop-el.messages.clientHeight<100;el.messages.innerHTML=messages.map(message=>{const role=message.role;const avatar=role==='assistant'?'<div class="avatar">AI</div>':'';const tools=(message.tool_calls||[]).map(tool=>`<div class="tool-card"><div class="tool-top"><span>${escapeHtml(tool.name)}</span><span class="tool-status ${escapeHtml(tool.status)}">${escapeHtml(tool.status)}</span></div><pre>${escapeHtml(tool.output||tool.arguments)}</pre></div>`).join('');const image=message.image_url?`<img class="generated-image" src="${escapeHtml(message.image_url)}" alt="Generated image">`:'';const text=message.text||(message.streaming?'Thinking…':'');return `<article class="message-row ${role}">${avatar}<div class="message"><div class="message-bubble ${message.streaming?'typing':''}">${escapeHtml(text)}${tools}${image}</div><div class="message-meta">${formatTime(message.created_at)}</div></div></article>`}).join('');if(nearBottom||app.lastRevision<2)el.messages.scrollTop=el.messages.scrollHeight}
function currentSettings(){const fallback=app.state?.settings||{};return{backend:$('#backendSegments button.active')?.dataset.backend||fallback.backend||'codex_gpt_live',auth_mode:el.authMode.value,model:el.modelInput.value.trim()||'gpt-realtime-2.1',voice:el.voiceInput.value,thinking_level:el.thinkingInput.value,system_prompt:el.systemPrompt.value,send_screenshot:el.sendScreenshot.checked,image_model:el.imageModelInput.value.trim()||'gpt-image-2',image_resolution:el.imageResolutionInput.value}}
function queueSettingsSave(){el.settingsSaved.textContent='Saving…';clearTimeout(app.settingsTimer);app.settingsTimer=setTimeout(saveSettings,280)}
async function saveSettings(){try{await request('/api/settings',{method:'POST',body:JSON.stringify(currentSettings())});el.settingsSaved.textContent='Synced with backend'}catch(error){el.settingsSaved.textContent=error.message}}
async function toggleConnection(){const connected=['live','connecting','reconnecting'].includes(app.state?.connection);try{if(connected){if(app.mic)await stopMicrophone();await request('/api/disconnect',{method:'POST',body:'{}'});return}await saveSettings();await request('/api/connect',{method:'POST',body:JSON.stringify({api_key:el.apiKey.value.trim()||null})});el.apiKey.value=''}catch(error){showError(error.message)}}
async function sendMessage(event){event.preventDefault();const text=el.composerInput.value.trim();if(!text)return;el.composerInput.value='';autoResizeComposer();try{await request('/api/message',{method:'POST',body:JSON.stringify({text})})}catch(error){showError(error.message)}}
function showError(message){el.errorBanner.textContent=message;el.errorBanner.classList.remove('hidden')}
function openSettings(open){el.settingsDrawer.classList.toggle('open',open);el.settingsDrawer.setAttribute('aria-hidden',String(!open));el.settingsScrim.classList.toggle('hidden',!open)}
function autoResizeComposer(){el.composerInput.style.height='auto';el.composerInput.style.height=`${Math.min(el.composerInput.scrollHeight,150)}px`}
async function toggleMicrophone(){if(app.mic)await stopMicrophone();else await startMicrophone()}
async function startMicrophone(){if(app.state?.connection!=='live')throw new Error('Connect a voice model first.');const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const context=new AudioContext({latencyHint:'interactive'});const source=context.createMediaStreamSource(stream);const processor=context.createScriptProcessor(2048,1,1);const mute=context.createGain();mute.gain.value=0;source.connect(processor);processor.connect(mute);mute.connect(context.destination);processor.onaudioprocess=event=>{if(!app.mic)return;const input=event.inputBuffer.getChannelData(0);const output=resampleFloat(input,context.sampleRate,24000);const pcm=new Int16Array(output.length);for(let i=0;i<output.length;i++){const sample=Math.max(-1,Math.min(1,output[i]));pcm[i]=sample<0?sample*0x8000:sample*0x7fff}if(app.ws?.readyState===WebSocket.OPEN)app.ws.send(pcm.buffer)};app.mic={stream,context,source,processor,mute};el.micButton.classList.add('active');el.micButton.title='Stop microphone'}
async function stopMicrophone(){const mic=app.mic;if(!mic)return;app.mic=null;mic.processor.disconnect();mic.source.disconnect();mic.mute.disconnect();mic.stream.getTracks().forEach(track=>track.stop());await mic.context.close();el.micButton.classList.remove('active');el.micButton.title='Start microphone'}
function resampleFloat(input,sourceRate,targetRate){if(sourceRate===targetRate)return input;const ratio=sourceRate/targetRate;const length=Math.max(1,Math.floor(input.length/ratio));const output=new Float32Array(length);for(let i=0;i<length;i++){const sourceIndex=i*ratio;const left=Math.floor(sourceIndex);const right=Math.min(left+1,input.length-1);const mix=sourceIndex-left;output[i]=input[left]*(1-mix)+input[right]*mix}return output}
function playPcm(arrayBuffer){if(!arrayBuffer.byteLength)return;if(!app.audioContext)app.audioContext=new AudioContext({sampleRate:24000,latencyHint:'interactive'});const context=app.audioContext;if(context.state==='suspended')context.resume();const samples=new Int16Array(arrayBuffer);const buffer=context.createBuffer(1,samples.length,24000);const channel=buffer.getChannelData(0);for(let i=0;i<samples.length;i++)channel[i]=samples[i]/32768;const source=context.createBufferSource();source.buffer=buffer;source.connect(context.destination);const now=context.currentTime;app.playbackTime=Math.max(now+.03,app.playbackTime);source.start(app.playbackTime);app.playbackTime+=buffer.duration}
function bindEvents(){el.composerForm.addEventListener('submit',sendMessage);el.composerInput.addEventListener('input',autoResizeComposer);el.composerInput.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey)sendMessage(event)});el.connectButton.addEventListener('click',toggleConnection);el.drawerConnect.addEventListener('click',toggleConnection);el.clearButton.addEventListener('click',()=>request('/api/clear',{method:'POST',body:'{}'}));el.micButton.addEventListener('click',()=>toggleMicrophone().catch(error=>showError(error.message)));el.settingsToggle.addEventListener('click',()=>openSettings(true));el.settingsClose.addEventListener('click',()=>openSettings(false));el.settingsScrim.addEventListener('click',()=>openSettings(false));el.authMode.addEventListener('change',()=>{el.apiKeyGroup.classList.toggle('hidden',el.authMode.value!=='api_key');queueSettingsSave()});for(const input of[el.modelInput,el.voiceInput,el.thinkingInput,el.imageModelInput,el.imageResolutionInput,el.sendScreenshot,el.systemPrompt])input.addEventListener(input.tagName==='TEXTAREA'||input.type==='text'?'input':'change',queueSettingsSave);$$('#backendSegments button').forEach(button=>button.addEventListener('click',()=>{$$('#backendSegments button').forEach(other=>other.classList.remove('active'));button.classList.add('active');const defaults={codex_gpt_live:{voice:'ember',model:'gpt-realtime-2.1'},open_ai_realtime:{voice:'marin',model:'gpt-realtime-2.1'},codex_text:{voice:el.voiceInput.value,model:'gpt-5.6-luna'}}[button.dataset.backend];el.voiceInput.value=defaults.voice;el.modelInput.value=defaults.model;queueSettingsSave()}))}
async function init(){bindEvents();connectWebSocket();try{applyState(await request('/api/state'))}catch(error){showError(`Backend unavailable: ${error.message}`)}setInterval(async()=>{if(app.ws?.readyState===WebSocket.OPEN)return;try{applyState(await request('/api/state'))}catch(_){}},2500)}
init();
